##### Copyright 2019 The TensorFlow Authors.

In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# 对结构化数据进行分类

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://tensorflow.google.cn/tutorials/structured_data/feature_columns">
    <img src="https://tensorflow.google.cn/images/tf_logo_32px.png" />
    在 tensorflow.google.cn 上查看</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs-l10n/blob/master/site/zh-cn/tutorials/structured_data/feature_columns.ipynb">
    <img src="https://tensorflow.google.cn/images/colab_logo_32px.png" />
    在 Google Colab 运行</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/docs-l10n/blob/master/site/zh-cn/tutorials/structured_data/feature_columns.ipynb">
    <img src="https://tensorflow.google.cn/images/GitHub-Mark-32px.png" />
    在 Github 上查看源代码</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/docs-l10n/site/zh-cn/tutorials/structured_data/feature_columns.ipynb"><img src="https://tensorflow.google.cn/images/download_logo_32px.png" />下载此 notebook</a>
  </td>
</table>

Note: 我们的 TensorFlow 社区翻译了这些文档。因为社区翻译是尽力而为， 所以无法保证它们是最准确的，并且反映了最新的
[官方英文文档](https://tensorflow.google.cn/?hl=en)。如果您有改进此翻译的建议， 请提交 pull request 到
[tensorflow/docs](https://github.com/tensorflow/docs) GitHub 仓库。要志愿地撰写或者审核译文，请加入
[docs-zh-cn@tensorflow.org Google Group](https://groups.google.com/a/tensorflow.org/forum/#!forum/docs-zh-cn)。

本教程演示了如何对结构化数据进行分类（例如，CSV 中的表格数据）。我们将使用 [Keras](https://tensorflow.google.cn/guide/keras)  来定义模型，将[特征列（feature columns）](https://tensorflow.google.cn/guide/feature_columns) 作为从 CSV 中的列（columns）映射到用于训练模型的特征（features）的桥梁。本教程包括了以下内容的完整代码：

* 用 [Pandas](https://pandas.pydata.org/) 导入 CSV 文件。
* 用 [tf.data](https://tensorflow.google.cn/guide/datasets) 建立了一个输入流水线（pipeline），用于对行进行分批（batch）和随机排序（shuffle）。
* 用特征列将 CSV 中的列映射到用于训练模型的特征。
* 用 Keras 构建，训练并评估模型。

## 数据集

我们将使用一个小型 [数据集](https://archive.ics.uci.edu/ml/datasets/heart+Disease)，该数据集由克利夫兰心脏病诊所基金会（Cleveland Clinic Foundation for Heart Disease）提供。CSV 中有几百行数据。每行描述了一个病人（patient），每列描述了一个属性（attribute）。我们将使用这些信息来预测一位病人是否患有心脏病，这是在该数据集上的二分类任务。

下面是该数据集的[描述](https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/heart-disease.names)。 请注意，有数值（numeric）和类别（categorical）类型的列。

>列| 描述| 特征类型 | 数据类型
>------------|--------------------|----------------------|-----------------
>Age | 年龄以年为单位 | Numerical | integer
>Sex | （1 = 男；0 = 女） | Categorical | integer
>CP | 胸痛类型（0，1，2，3，4）| Categorical | integer
>Trestbpd | 静息血压（入院时，以mm Hg计） | Numerical | integer
>Chol | 血清胆固醇（mg/dl） | Numerical | integer
>FBS |（空腹血糖> 120 mg/dl）（1 = true；0 = false）| Categorical | integer
>RestECG | 静息心电图结果（0，1，2）| Categorical | integer
>Thalach | 达到的最大心率 | Numerical | integer
>Exang | 运动诱发心绞痛（1 =是；0 =否）| Categorical | integer
>Oldpeak | 与休息时相比由运动引起的 ST 节段下降|Numerical | integer
>Slope | 在运动高峰 ST 段的斜率 | Numerical | float
>CA | 荧光透视法染色的大血管动脉（0-3）的数量 | Numerical | integer
>Thal | 3 =正常；6 =固定缺陷；7 =可逆缺陷 | Categorical | string
>Target | 心脏病诊断（1 = true；0 = false） | Classification | integer

## 导入 TensorFlow 和其他库

In [2]:
!pip install -q sklearn

You should consider upgrading via the '/tmpfs/src/tf_docs_env/bin/python -m pip install --upgrade pip' command.


In [3]:
import numpy as np
import pandas as pd

import tensorflow as tf

from tensorflow import feature_column
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

## 使用 Pandas 创建一个 dataframe

[Pandas](https://pandas.pydata.org/) 是一个 Python 库，它有许多有用的实用程序，用于加载和处理结构化数据。我们将使用 Pandas 从 URL下载数据集，并将其加载到 dataframe 中。

In [4]:
URL = 'https://storage.googleapis.com/applied-dl/heart.csv'
dataframe = pd.read_csv(URL)
dataframe.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca        thal  target  
0   0       fixed       0  
1   3      normal       1  
2   2  reversible       0  
3   0      normal       0  
4   0      normal       0

## 将 dataframe 拆分为训练、验证和测试集

我们下载的数据集是一个 CSV 文件。 我们将其拆分为训练、验证和测试集。

In [5]:
train, test = train_test_split(dataframe, test_size=0.2)
train, val = train_test_split(train, test_size=0.2)
print(len(train), 'train examples')
print(len(val), 'validation examples')
print(len(test), 'test examples')

193 train examples
49 validation examples
61 test examples


## 用 tf.data 创建输入流水线

接下来，我们将使用 [tf.data](https://tensorflow.google.cn/guide/datasets) 包装 dataframe。这让我们能将特征列作为一座桥梁，该桥梁将 Pandas dataframe 中的列映射到用于训练模型的特征。如果我们使用一个非常大的 CSV 文件（非常大以至于它不能放入内存），我们将使用 tf.data 直接从磁盘读取它。本教程不涉及这一点。

In [6]:
# 一种从 Pandas Dataframe 创建 tf.data 数据集的实用程序方法（utility method）
def df_to_dataset(dataframe, shuffle=True, batch_size=32):
  dataframe = dataframe.copy()
  labels = dataframe.pop('target')
  ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
  if shuffle:
    ds = ds.shuffle(buffer_size=len(dataframe))
  ds = ds.batch(batch_size)
  return ds

In [7]:
batch_size = 5 # 小批量大小用于演示
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

## 理解输入流水线

现在我们已经创建了输入流水线，让我们调用它来查看它返回的数据的格式。 我们使用了一小批量大小来保持输出的可读性。

In [8]:
for feature_batch, label_batch in train_ds.take(1):
  print('Every feature:', list(feature_batch.keys()))
  print('A batch of ages:', feature_batch['age'])
  print('A batch of targets:', label_batch )

Every feature: ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal']
A batch of ages: tf.Tensor([58 44 44 50 54], shape=(5,), dtype=int64)
A batch of targets: tf.Tensor([0 1 0 0 1], shape=(5,), dtype=int64)


我们可以看到数据集返回了一个字典，该字典从列名称（来自 dataframe）映射到 dataframe 中行的列值。

## 演示几种特征列
TensorFlow 提供了多种特征列。本节中，我们将创建几类特征列，并演示特征列如何转换 dataframe 中的列。

In [9]:
# 我们将使用该批数据演示几种特征列
example_batch = next(iter(train_ds))[0]

In [10]:
# 用于创建一个特征列
# 并转换一批次数据的一个实用程序方法
def demo(feature_column):
  feature_layer = layers.DenseFeatures(feature_column)
  print(feature_layer(example_batch).numpy())

### 数值列
一个特征列的输出将成为模型的输入（使用上面定义的 demo 函数，我们将能准确地看到 dataframe 中的每列的转换方式）。 [数值列（numeric column）](https://tensorflow.google.cn/api_docs/python/tf/feature_column/numeric_column) 是最简单的列类型。它用于表示实数特征。使用此列时，模型将从 dataframe 中接收未更改的列值。

In [11]:
age = feature_column.numeric_column("age")
demo(age)


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



[[63.]
 [62.]
 [59.]
 [74.]
 [68.]]


在这个心脏病数据集中，dataframe 中的大多数列都是数值列。

### 分桶列
通常，您不希望将数字直接输入模型，而是根据数值范围将其值分成不同的类别。考虑代表一个人年龄的原始数据。我们可以用 [分桶列（bucketized column）](https://tensorflow.google.cn/api_docs/python/tf/feature_column/bucketized_column)将年龄分成几个分桶（buckets），而不是将年龄表示成数值列。请注意下面的 one-hot 数值表示每行匹配的年龄范围。

In [12]:
age_buckets = feature_column.bucketized_column(age, boundaries=[18, 25, 30, 35, 40, 45, 50, 55, 60, 65])
demo(age_buckets)


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


### 分类列
在此数据集中，thal 用字符串表示（如 'fixed'，'normal'，或 'reversible'）。我们无法直接将字符串提供给模型。相反，我们必须首先将它们映射到数值。分类词汇列（categorical vocabulary columns）提供了一种用 one-hot 向量表示字符串的方法（就像您在上面看到的年龄分桶一样）。词汇表可以用 [categorical_column_with_vocabulary_list](https://tensorflow.google.cn/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_list) 作为 list 传递，或者用 [categorical_column_with_vocabulary_file](https://tensorflow.google.cn/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file) 从文件中加载。

In [13]:
thal = feature_column.categorical_column_with_vocabulary_list(
      'thal', ['fixed', 'normal', 'reversible'])

thal_one_hot = feature_column.indicator_column(thal)
demo(thal_one_hot)


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



[[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


在更复杂的数据集中，许多列都是分类列（如 strings）。在处理分类数据时，特征列最有价值。尽管在该数据集中只有一列分类列，但我们将使用它来演示在处理其他数据集时，可以使用的几种重要的特征列。

### 嵌入列
假设我们不是只有几个可能的字符串，而是每个类别有数千（或更多）值。 由于多种原因，随着类别数量的增加，使用 one-hot 编码训练神经网络变得不可行。我们可以使用嵌入列来克服此限制。[嵌入列（embedding column）](https://tensorflow.google.cn/api_docs/python/tf/feature_column/embedding_column)将数据表示为一个低维度密集向量，而非多维的 one-hot 向量，该低维度密集向量可以包含任何数，而不仅仅是 0 或 1。嵌入的大小（在下面的示例中为 8）是必须调整的参数。

关键点：当分类列具有许多可能的值时，最好使用嵌入列。我们在这里使用嵌入列用于演示目的，为此您有一个完整的示例，以在将来可以修改用于其他数据集。

In [14]:
# 注意到嵌入列的输入是我们之前创建的类别列
thal_embedding = feature_column.embedding_column(thal, dimension=8)
demo(thal_embedding)


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



[[ 0.00543996 -0.5059579   0.0389499  -0.20236802  0.11128058  0.59121
   0.14891742 -0.11942385]
 [ 0.00543996 -0.5059579   0.0389499  -0.20236802  0.11128058  0.59121
   0.14891742 -0.11942385]
 [ 0.09787773 -0.5861865  -0.3713007  -0.1747458  -0.01538717  0.55458224
   0.12537968 -0.11748305]
 [-0.00701649  0.28291813  0.23547529 -0.5102454  -0.5388726   0.5154376
   0.12235989  0.44484815]
 [ 0.00543996 -0.5059579   0.0389499  -0.20236802  0.11128058  0.59121
   0.14891742 -0.11942385]]


### 经过哈希处理的特征列

表示具有大量数值的分类列的另一种方法是使用 [categorical_column_with_hash_bucket](https://tensorflow.google.cn/api_docs/python/tf/feature_column/categorical_column_with_hash_bucket)。该特征列计算输入的一个哈希值，然后选择一个 `hash_bucket_size` 分桶来编码字符串。使用此列时，您不需要提供词汇表，并且可以选择使 hash_buckets 的数量远远小于实际类别的数量以节省空间。

关键点：该技术的一个重要缺点是可能存在冲突，不同的字符串被映射到同一个范围。实际上，无论如何，经过哈希处理的特征列对某些数据集都有效。

In [15]:
thal_hashed = feature_column.categorical_column_with_hash_bucket(
      'thal', hash_bucket_size=1000)
demo(feature_column.indicator_column(thal_hashed))


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


### 组合的特征列
将多种特征组合到一个特征中，称为[特征组合（feature crosses）](https://developers.google.com/machine-learning/glossary/#feature_cross)，它让模型能够为每种特征组合学习单独的权重。此处，我们将创建一个 age 和 thal 组合的新特征。请注意，`crossed_column` 不会构建所有可能组合的完整列表（可能非常大）。相反，它由 `hashed_column` 支持，因此您可以选择表的大小。

In [16]:
crossed_feature = feature_column.crossed_column([age_buckets, thal], hash_bucket_size=1000)
demo(feature_column.indicator_column(crossed_feature))


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## 选择要使用的列
我们已经了解了如何使用几种类型的特征列。 现在我们将使用它们来训练模型。本教程的目标是向您展示使用特征列所需的完整代码（例如，机制）。我们任意地选择了几列来训练我们的模型。

关键点：如果您的目标是建立一个准确的模型，请尝试使用您自己的更大的数据集，并仔细考虑哪些特征最有意义，以及如何表示它们。

In [17]:
feature_columns = []

# 数值列
for header in ['age', 'trestbps', 'chol', 'thalach', 'oldpeak', 'slope', 'ca']:
  feature_columns.append(feature_column.numeric_column(header))

# 分桶列
age_buckets = feature_column.bucketized_column(age, boundaries=[18, 25, 30, 35, 40, 45, 50, 55, 60, 65])
feature_columns.append(age_buckets)

# 分类列
thal = feature_column.categorical_column_with_vocabulary_list(
      'thal', ['fixed', 'normal', 'reversible'])
thal_one_hot = feature_column.indicator_column(thal)
feature_columns.append(thal_one_hot)

# 嵌入列
thal_embedding = feature_column.embedding_column(thal, dimension=8)
feature_columns.append(thal_embedding)

# 组合列
crossed_feature = feature_column.crossed_column([age_buckets, thal], hash_bucket_size=1000)
crossed_feature = feature_column.indicator_column(crossed_feature)
feature_columns.append(crossed_feature)

### 建立一个新的特征层
现在我们已经定义了我们的特征列，我们将使用[密集特征（DenseFeatures）](https://tensorflow.google.cn/versions/r2.0/api_docs/python/tf/keras/layers/DenseFeatures)层将特征列输入到我们的 Keras 模型中。

In [18]:
feature_layer = tf.keras.layers.DenseFeatures(feature_columns)

之前，我们使用一个小批量大小来演示特征列如何运转。我们将创建一个新的更大批量的输入流水线。

In [19]:
batch_size = 32
train_ds = df_to_dataset(train, batch_size=batch_size)
val_ds = df_to_dataset(val, shuffle=False, batch_size=batch_size)
test_ds = df_to_dataset(test, shuffle=False, batch_size=batch_size)

## 创建，编译和训练模型

In [20]:
model = tf.keras.Sequential([
  feature_layer,
  layers.Dense(128, activation='relu'),
  layers.Dense(128, activation='relu'),
  layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'],
              run_eagerly=True)

model.fit(train_ds,
          validation_data=val_ds,
          epochs=5)

Epoch 1/5


array([[57],
       [45],
       [49],
       [67],
       [54],
       [70],
       [54],
       [52],
       [52],
       [44],
       [57],
       [43],
       [62],
       [59],
       [62],
       [58],
       [42],
       [68],
       [56],
       [46],
       [44],
       [40],
       [52],
       [63],
       [57],
       [56],
       [37],
       [64],
       [43],
       [34],
       [57],
       [51]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[3],
       [4],
       [2],
       [4],
       [3],
       [3],
       [3],
   


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



1/7 [===>..........................] - ETA: 0s - loss: 1.9156 - accuracy: 0.8438

array([[64],
       [62],
       [57],
       [64],
       [70],
       [54],
       [64],
       [67],
       [61],
       [56],
       [41],
       [42],
       [50],
       [47],
       [58],
       [60],
       [41],
       [57],
       [55],
       [42],
       [50],
       [44],
       [58],
       [67],
       [66],
       [37],
       [45],
       [67],
       [62],
       [59],
       [56],
       [66]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[3],
       [2],
       [4],
       [1],
       [4],
       [4],
       [4],
   

array([[63],
       [43],
       [52],
       [54],
       [65],
       [45],
       [44],
       [34],
       [40],
       [51],
       [64],
       [47],
       [54],
       [63],
       [60],
       [54],
       [41],
       [53],
       [56],
       [54],
       [57],
       [59],
       [43],
       [67],
       [68],
       [53],
       [44],
       [58],
       [46],
       [59],
       [47],
       [53]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[4],
       [4],
       [4],
       [3],
       [3],
       [4],
       [3],
   

3/7 [===========>..................] - ETA: 0s - loss: 2.4590 - accuracy: 0.6354

array([[71],
       [61],
       [41],
       [48],
       [54],
       [51],
       [43],
       [50],
       [52],
       [57],
       [59],
       [67],
       [56],
       [45],
       [42],
       [49],
       [44],
       [54],
       [50],
       [56],
       [47],
       [60],
       [61],
       [55],
       [57],
       [58],
       [46],
       [49],
       [46],
       [55],
       [68],
       [39]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[2],
       [4],
       [3],
       [4],
       [4],
       [3],
       [4],
   

array([[58],
       [51],
       [54],
       [51],
       [50],
       [66],
       [53],
       [46],
       [46],
       [42],
       [58],
       [29],
       [43],
       [60],
       [57],
       [35],
       [74],
       [65],
       [41],
       [45],
       [58],
       [56],
       [58],
       [57],
       [45],
       [51],
       [64],
       [44],
       [50],
       [59],
       [67],
       [50]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[4],
       [1],
       [4],
       [3],
       [2],
       [2],
       [3],
   

5/7 [====================>.........] - ETA: 0s - loss: 2.0828 - accuracy: 0.5938

array([[43],
       [55],
       [44],
       [58],
       [48],
       [62],
       [62],
       [52],
       [58],
       [60],
       [38],
       [42],
       [57],
       [69],
       [57],
       [57],
       [55],
       [63],
       [49],
       [63],
       [60],
       [59],
       [64],
       [59],
       [68],
       [62],
       [59],
       [62],
       [42],
       [53],
       [59],
       [64]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[4],
       [4],
       [3],
       [4],
       [2],
       [4],
       [3],
   

Consider rewriting this model with the Functional API.


7/7 [==============================] - ETA: 0s - loss: 2.0670 - accuracy: 0.6062

array([[62],
       [65],
       [60],
       [35],
       [48],
       [66],
       [42],
       [44],
       [67],
       [71],
       [45],
       [65],
       [52],
       [76],
       [48],
       [51],
       [61],
       [51],
       [66],
       [51],
       [60],
       [52],
       [49],
       [57],
       [54],
       [68],
       [41],
       [62],
       [59],
       [45],
       [59],
       [55]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[4],
       [4],
       [3],
       [2],
       [4],
       [4],
       [3],
   

array([[77],
       [39],
       [60],
       [41],
       [56],
       [51],
       [59],
       [41],
       [60],
       [64],
       [64],
       [70],
       [62],
       [58],
       [58],
       [67],
       [35]])>, 'sex': <tf.Tensor: shape=(17, 1), dtype=int64, numpy=
array([[1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0]])>, 'cp': <tf.Tensor: shape=(17, 1), dtype=int64, numpy=
array([[4],
       [4],
       [4],
       [2],
       [3],
       [3],
       [2],
       [2],
       [4],
       [4],
       [4],
       [2],
       [4],
       [4],
       [4],
       [4],
       [4]])>, 'trestbps': <tf.Tensor: shape=(17, 1), dtype=int64, numpy=
array([[125],
       [118],
       [130],
       [130],
       [130],
       [ 94],
       [140],
       [120],
       [125],
       [130],
       [120],
       [156],
       [160],
       [125],


7/7 [==============================] - 0s 44ms/step - loss: 2.0670 - accuracy: 0.6062 - val_loss: 1.8843 - val_accuracy: 0.7347


Epoch 2/5
array([[57],
       [56],
       [50],
       [52],
       [56],
       [61],
       [68],
       [34],
       [58],
       [50],
       [40],
       [51],
       [47],
       [35],
       [45],
       [64],
       [44],
       [44],
       [38],
       [57],
       [58],
       [51],
       [59],
       [43],
       [41],
       [55],
       [47],
       [56],
       [54],
       [43],
       [64],
       [57]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[4],
       [4],
       [3],
       [1],
       [4],
       [4],
     

1/7 [===>..........................] - ETA: 0s - loss: 2.3728 - accuracy: 0.6875

array([[53],
       [43],
       [49],
       [37],
       [60],
       [58],
       [41],
       [45],
       [40],
       [59],
       [63],
       [60],
       [42],
       [45],
       [49],
       [57],
       [67],
       [50],
       [58],
       [50],
       [51],
       [68],
       [44],
       [59],
       [55],
       [52],
       [54],
       [44],
       [43],
       [54],
       [58],
       [41]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[4],
       [4],
       [4],
       [3],
       [4],
       [4],
       [3],
   

array([[37],
       [44],
       [58],
       [54],
       [29],
       [56],
       [62],
       [62],
       [44],
       [57],
       [67],
       [50],
       [56],
       [56],
       [61],
       [51],
       [67],
       [58],
       [42],
       [66],
       [52],
       [57],
       [46],
       [48],
       [70],
       [65],
       [53],
       [60],
       [57],
       [34],
       [57],
       [50]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[3],
       [3],
       [2],
       [4],
       [2],
       [4],
       [4],
   

3/7 [===========>..................] - ETA: 0s - loss: 2.1748 - accuracy: 0.6562

array([[56],
       [58],
       [60],
       [54],
       [46],
       [67],
       [67],
       [53],
       [46],
       [49],
       [43],
       [54],
       [68],
       [43],
       [61],
       [59],
       [50],
       [62],
       [62],
       [54],
       [57],
       [45],
       [39],
       [74],
       [45],
       [63],
       [48],
       [68],
       [62],
       [64],
       [63],
       [58]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[4],
       [4],
       [3],
       [4],
       [3],
       [4],
       [4],
   

array([[49],
       [65],
       [43],
       [42],
       [54],
       [42],
       [53],
       [57],
       [64],
       [67],
       [56],
       [66],
       [59],
       [52],
       [57],
       [42],
       [71],
       [64],
       [58],
       [55],
       [69],
       [52],
       [60],
       [59],
       [42],
       [51],
       [46],
       [53],
       [51],
       [55],
       [66],
       [64]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[3],
       [3],
       [4],
       [2],
       [3],
       [3],
       [4],
   

5/7 [====================>.........] - ETA: 0s - loss: 1.5868 - accuracy: 0.6313

array([[46],
       [47],
       [57],
       [64],
       [41],
       [62],
       [62],
       [57],
       [59],
       [54],
       [60],
       [58],
       [70],
       [46],
       [57],
       [41],
       [64],
       [63],
       [59],
       [52],
       [42],
       [59],
       [55],
       [62],
       [59],
       [51],
       [63],
       [44],
       [47],
       [45],
       [67],
       [44]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[2],
       [3],
       [3],
       [3],
       [2],
       [4],
       [2],
   

Consider rewriting this model with the Functional API.


7/7 [==============================] - ETA: 0s - loss: 1.5046 - accuracy: 0.5803

array([[62],
       [65],
       [60],
       [35],
       [48],
       [66],
       [42],
       [44],
       [67],
       [71],
       [45],
       [65],
       [52],
       [76],
       [48],
       [51],
       [61],
       [51],
       [66],
       [51],
       [60],
       [52],
       [49],
       [57],
       [54],
       [68],
       [41],
       [62],
       [59],
       [45],
       [59],
       [55]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[4],
       [4],
       [3],
       [2],
       [4],
       [4],
       [3],
   

array([[77],
       [39],
       [60],
       [41],
       [56],
       [51],
       [59],
       [41],
       [60],
       [64],
       [64],
       [70],
       [62],
       [58],
       [58],
       [67],
       [35]])>, 'sex': <tf.Tensor: shape=(17, 1), dtype=int64, numpy=
array([[1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0]])>, 'cp': <tf.Tensor: shape=(17, 1), dtype=int64, numpy=
array([[4],
       [4],
       [4],
       [2],
       [3],
       [3],
       [2],
       [2],
       [4],
       [4],
       [4],
       [2],
       [4],
       [4],
       [4],
       [4],
       [4]])>, 'trestbps': <tf.Tensor: shape=(17, 1), dtype=int64, numpy=
array([[125],
       [118],
       [130],
       [130],
       [130],
       [ 94],
       [140],
       [120],
       [125],
       [130],
       [120],
       [156],
       [160],
       [125],


7/7 [==============================] - 0s 42ms/step - loss: 1.5046 - accuracy: 0.5803 - val_loss: 0.5387 - val_accuracy: 0.7551


Epoch 3/5
array([[49],
       [43],
       [58],
       [42],
       [42],
       [59],
       [62],
       [64],
       [56],
       [59],
       [60],
       [67],
       [58],
       [43],
       [54],
       [52],
       [63],
       [37],
       [44],
       [34],
       [49],
       [63],
       [50],
       [64],
       [56],
       [57],
       [68],
       [42],
       [47],
       [62],
       [53],
       [35]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[3],
       [4],
       [4],
       [4],
       [3],
       [1],
     

1/7 [===>..........................] - ETA: 0s - loss: 0.4726 - accuracy: 0.7500

array([[38],
       [55],
       [61],
       [53],
       [47],
       [52],
       [59],
       [44],
       [56],
       [52],
       [54],
       [74],
       [53],
       [58],
       [57],
       [57],
       [50],
       [43],
       [67],
       [59],
       [45],
       [45],
       [66],
       [60],
       [64],
       [68],
       [69],
       [67],
       [51],
       [58],
       [57],
       [42]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [4],
       [4],
       [4],
       [3],
       [2],
       [0],
   

array([[59],
       [63],
       [62],
       [48],
       [40],
       [50],
       [29],
       [67],
       [51],
       [45],
       [65],
       [41],
       [45],
       [46],
       [43],
       [57],
       [64],
       [55],
       [41],
       [41],
       [61],
       [57],
       [52],
       [49],
       [66],
       [58],
       [59],
       [62],
       [63],
       [62],
       [58],
       [66]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[4],
       [4],
       [4],
       [2],
       [4],
       [4],
       [2],
   

3/7 [===========>..................] - ETA: 0s - loss: 0.9738 - accuracy: 0.6979

array([[58],
       [60],
       [58],
       [44],
       [59],
       [57],
       [53],
       [54],
       [54],
       [45],
       [64],
       [57],
       [60],
       [46],
       [68],
       [47],
       [64],
       [40],
       [62],
       [42],
       [44],
       [42],
       [43],
       [39],
       [61],
       [44],
       [50],
       [54],
       [49],
       [50],
       [68],
       [46]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[4],
       [4],
       [1],
       [2],
       [1],
       [4],
       [4],
   

array([[41],
       [62],
       [45],
       [71],
       [42],
       [47],
       [51],
       [54],
       [59],
       [67],
       [57],
       [56],
       [58],
       [54],
       [67],
       [63],
       [37],
       [34],
       [43],
       [65],
       [46],
       [44],
       [60],
       [70],
       [52],
       [64],
       [56],
       [55],
       [50],
       [51],
       [70],
       [55]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[3],
       [4],
       [4],
       [2],
       [4],
       [3],
       [3],
   

5/7 [====================>.........] - ETA: 0s - loss: 1.0254 - accuracy: 0.7188

array([[54],
       [59],
       [58],
       [44],
       [43],
       [56],
       [55],
       [57],
       [54],
       [54],
       [57],
       [57],
       [57],
       [48],
       [64],
       [51],
       [52],
       [51],
       [56],
       [50],
       [46],
       [56],
       [59],
       [60],
       [51],
       [67],
       [53],
       [44],
       [46],
       [41],
       [58],
       [57]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[4],
       [1],
       [4],
       [2],
       [3],
       [4],
       [4],
   

Consider rewriting this model with the Functional API.


7/7 [==============================] - ETA: 0s - loss: 1.0386 - accuracy: 0.6995

array([[62],
       [65],
       [60],
       [35],
       [48],
       [66],
       [42],
       [44],
       [67],
       [71],
       [45],
       [65],
       [52],
       [76],
       [48],
       [51],
       [61],
       [51],
       [66],
       [51],
       [60],
       [52],
       [49],
       [57],
       [54],
       [68],
       [41],
       [62],
       [59],
       [45],
       [59],
       [55]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[4],
       [4],
       [3],
       [2],
       [4],
       [4],
       [3],
   

array([[77],
       [39],
       [60],
       [41],
       [56],
       [51],
       [59],
       [41],
       [60],
       [64],
       [64],
       [70],
       [62],
       [58],
       [58],
       [67],
       [35]])>, 'sex': <tf.Tensor: shape=(17, 1), dtype=int64, numpy=
array([[1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0]])>, 'cp': <tf.Tensor: shape=(17, 1), dtype=int64, numpy=
array([[4],
       [4],
       [4],
       [2],
       [3],
       [3],
       [2],
       [2],
       [4],
       [4],
       [4],
       [2],
       [4],
       [4],
       [4],
       [4],
       [4]])>, 'trestbps': <tf.Tensor: shape=(17, 1), dtype=int64, numpy=
array([[125],
       [118],
       [130],
       [130],
       [130],
       [ 94],
       [140],
       [120],
       [125],
       [130],
       [120],
       [156],
       [160],
       [125],


7/7 [==============================] - 0s 42ms/step - loss: 1.0386 - accuracy: 0.6995 - val_loss: 0.6039 - val_accuracy: 0.6531


Epoch 4/5
array([[52],
       [58],
       [49],
       [60],
       [34],
       [41],
       [58],
       [58],
       [59],
       [52],
       [49],
       [57],
       [42],
       [57],
       [67],
       [44],
       [62],
       [53],
       [50],
       [48],
       [58],
       [58],
       [53],
       [42],
       [56],
       [45],
       [60],
       [62],
       [44],
       [57],
       [65],
       [46]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[4],
       [2],
       [4],
       [4],
       [1],
       [3],
     

1/7 [===>..........................] - ETA: 0s - loss: 0.5663 - accuracy: 0.6875

array([[63],
       [57],
       [44],
       [41],
       [46],
       [66],
       [51],
       [46],
       [62],
       [58],
       [41],
       [68],
       [58],
       [64],
       [60],
       [63],
       [45],
       [57],
       [52],
       [59],
       [29],
       [42],
       [63],
       [56],
       [58],
       [40],
       [55],
       [67],
       [52],
       [64],
       [43],
       [42]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[3],
       [2],
       [3],
       [2],
       [4],
       [4],
       [4],
   

array([[59],
       [66],
       [55],
       [43],
       [56],
       [45],
       [64],
       [57],
       [57],
       [67],
       [44],
       [54],
       [41],
       [63],
       [54],
       [49],
       [46],
       [62],
       [68],
       [56],
       [64],
       [59],
       [54],
       [43],
       [56],
       [69],
       [59],
       [58],
       [54],
       [64],
       [39],
       [61]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[0],
       [2],
       [2],
       [4],
       [4],
       [4],
       [1],
   

3/7 [===========>..................] - ETA: 0s - loss: 0.6564 - accuracy: 0.6562

array([[35],
       [62],
       [44],
       [57],
       [64],
       [67],
       [62],
       [68],
       [50],
       [53],
       [48],
       [59],
       [49],
       [43],
       [50],
       [51],
       [54],
       [44],
       [65],
       [50],
       [56],
       [57],
       [51],
       [64],
       [43],
       [50],
       [51],
       [50],
       [50],
       [44],
       [53],
       [37]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[4],
       [3],
       [2],
       [4],
       [4],
       [4],
       [3],
   

array([[57],
       [66],
       [47],
       [60],
       [37],
       [59],
       [54],
       [46],
       [62],
       [40],
       [68],
       [53],
       [57],
       [44],
       [54],
       [63],
       [54],
       [54],
       [47],
       [71],
       [51],
       [58],
       [34],
       [59],
       [52],
       [62],
       [61],
       [42],
       [64],
       [51],
       [55],
       [60]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[4],
       [4],
       [4],
       [4],
       [3],
       [4],
       [4],
   

5/7 [====================>.........] - ETA: 0s - loss: 0.6322 - accuracy: 0.6750

array([[70],
       [45],
       [47],
       [57],
       [43],
       [61],
       [42],
       [67],
       [46],
       [55],
       [51],
       [45],
       [59],
       [56],
       [55],
       [70],
       [41],
       [59],
       [57],
       [60],
       [43],
       [42],
       [67],
       [67],
       [38],
       [74],
       [56],
       [57],
       [52],
       [47],
       [54],
       [58]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[3],
       [4],
       [3],
       [3],
       [3],
       [4],
       [4],
   

Consider rewriting this model with the Functional API.


7/7 [==============================] - ETA: 0s - loss: 0.6209 - accuracy: 0.6943

array([[62],
       [65],
       [60],
       [35],
       [48],
       [66],
       [42],
       [44],
       [67],
       [71],
       [45],
       [65],
       [52],
       [76],
       [48],
       [51],
       [61],
       [51],
       [66],
       [51],
       [60],
       [52],
       [49],
       [57],
       [54],
       [68],
       [41],
       [62],
       [59],
       [45],
       [59],
       [55]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[4],
       [4],
       [3],
       [2],
       [4],
       [4],
       [3],
   

array([[77],
       [39],
       [60],
       [41],
       [56],
       [51],
       [59],
       [41],
       [60],
       [64],
       [64],
       [70],
       [62],
       [58],
       [58],
       [67],
       [35]])>, 'sex': <tf.Tensor: shape=(17, 1), dtype=int64, numpy=
array([[1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0]])>, 'cp': <tf.Tensor: shape=(17, 1), dtype=int64, numpy=
array([[4],
       [4],
       [4],
       [2],
       [3],
       [3],
       [2],
       [2],
       [4],
       [4],
       [4],
       [2],
       [4],
       [4],
       [4],
       [4],
       [4]])>, 'trestbps': <tf.Tensor: shape=(17, 1), dtype=int64, numpy=
array([[125],
       [118],
       [130],
       [130],
       [130],
       [ 94],
       [140],
       [120],
       [125],
       [130],
       [120],
       [156],
       [160],
       [125],


7/7 [==============================] - 0s 43ms/step - loss: 0.6209 - accuracy: 0.6943 - val_loss: 0.6867 - val_accuracy: 0.7347


Epoch 5/5
array([[60],
       [51],
       [49],
       [64],
       [54],
       [58],
       [42],
       [68],
       [70],
       [58],
       [66],
       [57],
       [57],
       [51],
       [60],
       [59],
       [55],
       [67],
       [49],
       [53],
       [50],
       [54],
       [65],
       [56],
       [48],
       [59],
       [63],
       [50],
       [59],
       [34],
       [54],
       [68]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[4],
       [3],
       [3],
       [1],
       [2],
       [4],
     

1/7 [===>..........................] - ETA: 0s - loss: 0.8235 - accuracy: 0.6562

array([[47],
       [51],
       [57],
       [54],
       [56],
       [52],
       [42],
       [74],
       [57],
       [58],
       [55],
       [50],
       [56],
       [59],
       [52],
       [51],
       [41],
       [60],
       [34],
       [67],
       [45],
       [62],
       [56],
       [51],
       [57],
       [45],
       [53],
       [64],
       [59],
       [58],
       [56],
       [69]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[3],
       [3],
       [3],
       [3],
       [4],
       [2],
       [4],
   

array([[37],
       [55],
       [68],
       [29],
       [57],
       [45],
       [44],
       [44],
       [45],
       [54],
       [49],
       [58],
       [52],
       [46],
       [58],
       [41],
       [60],
       [60],
       [63],
       [40],
       [58],
       [57],
       [44],
       [52],
       [43],
       [66],
       [51],
       [63],
       [68],
       [43],
       [67],
       [62]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[3],
       [4],
       [0],
       [2],
       [4],
       [2],
       [2],
   

3/7 [===========>..................] - ETA: 0s - loss: 0.7040 - accuracy: 0.6979

array([[46],
       [60],
       [67],
       [62],
       [59],
       [54],
       [54],
       [61],
       [57],
       [64],
       [42],
       [59],
       [62],
       [67],
       [38],
       [43],
       [54],
       [57],
       [59],
       [62],
       [58],
       [70],
       [57],
       [45],
       [53],
       [53],
       [51],
       [48],
       [41],
       [65],
       [53],
       [64]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[3],
       [4],
       [4],
       [4],
       [3],
       [3],
       [3],
   

array([[46],
       [57],
       [44],
       [42],
       [57],
       [43],
       [49],
       [41],
       [44],
       [63],
       [56],
       [62],
       [52],
       [43],
       [54],
       [58],
       [63],
       [71],
       [55],
       [62],
       [46],
       [52],
       [47],
       [61],
       [40],
       [50],
       [59],
       [47],
       [47],
       [62],
       [57],
       [64]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[3],
       [4],
       [4],
       [4],
       [4],
       [4],
       [2],
   

5/7 [====================>.........] - ETA: 0s - loss: 0.6946 - accuracy: 0.7000

array([[46],
       [61],
       [58],
       [42],
       [42],
       [50],
       [45],
       [43],
       [35],
       [56],
       [57],
       [37],
       [41],
       [58],
       [50],
       [56],
       [67],
       [44],
       [64],
       [44],
       [64],
       [44],
       [42],
       [43],
       [59],
       [67],
       [64],
       [50],
       [46],
       [66],
       [55],
       [39]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[2],
       [4],
       [4],
       [3],
       [2],
       [2],
       [4],
   

Consider rewriting this model with the Functional API.


7/7 [==============================] - ETA: 0s - loss: 0.6719 - accuracy: 0.7098

array([[62],
       [65],
       [60],
       [35],
       [48],
       [66],
       [42],
       [44],
       [67],
       [71],
       [45],
       [65],
       [52],
       [76],
       [48],
       [51],
       [61],
       [51],
       [66],
       [51],
       [60],
       [52],
       [49],
       [57],
       [54],
       [68],
       [41],
       [62],
       [59],
       [45],
       [59],
       [55]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[4],
       [4],
       [3],
       [2],
       [4],
       [4],
       [3],
   

array([[77],
       [39],
       [60],
       [41],
       [56],
       [51],
       [59],
       [41],
       [60],
       [64],
       [64],
       [70],
       [62],
       [58],
       [58],
       [67],
       [35]])>, 'sex': <tf.Tensor: shape=(17, 1), dtype=int64, numpy=
array([[1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0]])>, 'cp': <tf.Tensor: shape=(17, 1), dtype=int64, numpy=
array([[4],
       [4],
       [4],
       [2],
       [3],
       [3],
       [2],
       [2],
       [4],
       [4],
       [4],
       [2],
       [4],
       [4],
       [4],
       [4],
       [4]])>, 'trestbps': <tf.Tensor: shape=(17, 1), dtype=int64, numpy=
array([[125],
       [118],
       [130],
       [130],
       [130],
       [ 94],
       [140],
       [120],
       [125],
       [130],
       [120],
       [156],
       [160],
       [125],


7/7 [==============================] - 0s 41ms/step - loss: 0.6719 - accuracy: 0.7098 - val_loss: 0.5845 - val_accuracy: 0.7347


In [21]:
loss, accuracy = model.evaluate(test_ds)
print("Accuracy", accuracy)

array([[66],
       [56],
       [41],
       [61],
       [54],
       [39],
       [63],
       [61],
       [52],
       [39],
       [60],
       [54],
       [57],
       [57],
       [69],
       [53],
       [44],
       [59],
       [53],
       [63],
       [57],
       [57],
       [58],
       [52],
       [48],
       [61],
       [48],
       [70],
       [71],
       [65],
       [47],
       [57]])>, 'sex': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1]])>, 'cp': <tf.Tensor: shape=(32, 1), dtype=int64, numpy=
array([[3],
       [2],
       [3],
       [4],
       [2],
       [3],
       [2],
   

1/2 [==============>...............] - ETA: 0s - loss: 0.3588 - accuracy: 0.8125

array([[66],
       [40],
       [55],
       [65],
       [58],
       [41],
       [61],
       [60],
       [52],
       [58],
       [54],
       [56],
       [58],
       [65],
       [54],
       [69],
       [63],
       [55],
       [54],
       [58],
       [65],
       [44],
       [59],
       [63],
       [48],
       [35],
       [45],
       [46],
       [51]])>, 'sex': <tf.Tensor: shape=(29, 1), dtype=int64, numpy=
array([[0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0]])>, 'cp': <tf.Tensor: shape=(29, 1), dtype=int64, numpy=
array([[1],
       [4],
       [2],
       [4],
       [3],
       [4],
       [4],
       [1],
       [3],
       [3],
       [3],
       [2],
       [3],
      

2/2 [==============================] - 0s 14ms/step - loss: 0.4201 - accuracy: 0.8197


Accuracy 0.8196721076965332


关键点：通常使用更大更复杂的数据集进行深度学习，您将看到最佳结果。使用像这样的小数据集时，我们建议使用决策树或随机森林作为强有力的基准。本教程的目的不是训练一个准确的模型，而是演示处理结构化数据的机制，这样，在将来使用自己的数据集时，您有可以使用的代码作为起点。

### 下一步
了解有关分类结构化数据的更多信息的最佳方法是亲自尝试。我们建议寻找另一个可以使用的数据集，并使用和上面相似的代码，训练一个模型，对其分类。要提高准确率，请仔细考虑模型中包含哪些特征，以及如何表示这些特征。